schemalister/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView, RedirectView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'getschema.views.index', name='index'),
    url(r'^oauth_response/$', 'getschema.views.oauth_response', name='oauth_response'),
    url(r'^schema/(?P<schema_id>\d+)/$', 'getschema.views.view_schema', name='view_schema'),
    url(r'^logout/$', 'getschema.views.logout', name='logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^job_status/(?P<schema_id>\d+)/$', 'getschema.views.job_status'),
    url(r'^loading/(?P<schema_id>\d+)/$', 'getschema.views.loading'),
    url(r'^delete_schema/(?P<schema_id>\d+)/$', 'getschema.views.delete_schema', name='delete_schema'),
)

getschema/models.py
from django.db import models

class Schema(models.Model):
	org_id = models.CharField(max_length=255)
	org_name = models.CharField(max_length=255, blank=True)
	username = models.CharField(max_length=255, blank=True)
	api_version = models.CharField(max_length=255, blank=True)
	status = models.CharField(max_length=255, blank=True)
	error = models.TextField(blank=True)

	def sorted_objects(self):
		return self.object_set.order_by('label')

class Object(models.Model):
	schema = models.ForeignKey(Schema)
	label = models.CharField(max_length=255)
	api_name = models.CharField(max_length=255)

	def sorted_fields(self):
		return self.field_set.order_by('label')

class Field(models.Model):
	object = models.ForeignKey(Object)
	label = models.CharField(max_length=255)
	api_name = models.TextField(max_length=255)
	data_type = models.TextField()

class Debug(models.Model):
	debug = models.TextField()

getschema/forms.py
from django import forms
from django.forms import ModelForm

class LoginForm(forms.Form):
	environment = forms.CharField(required=False);
	api_version = forms.IntegerField(required=False)
	access_token = forms.CharField(required=False)
	instance_url = forms.CharField(required=False)
	org_id = forms.CharField(required=False)

getschema/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from getschema.models import Schema, Object, Field, Debug
from getschema.forms import LoginForm
from django.conf import settings
from getschema.tasks import get_objects_and_fields
import json	
import requests
from time import sleep

def index(request):
	
	if request.method == 'POST':

		login_form = LoginForm(request.POST)

		if login_form.is_valid():

			environment = login_form.cleaned_data['environment']
			api_version = login_form.cleaned_data['api_version']

			oauth_url = 'https://login.salesforce.com/services/oauth2/authorize'
			if environment == 'Sandbox':
				oauth_url = 'https://test.salesforce.com/services/oauth2/authorize'

			oauth_url = oauth_url + '?response_type=code&client_id=' + settings.SALESFORCE_CONSUMER_KEY + '&redirect_uri=' + settings.SALESFORCE_REDIRECT_URI + '&state='+ environment + str(api_version)
			
			return HttpResponseRedirect(oauth_url)
	else:
		login_form = LoginForm()

	return render_to_response('index.html', RequestContext(request,{'login_form': login_form}))

def oauth_response(request):

	error_exists = False
	error_message = ''
	username = ''
	org_name = ''

	# On page load
	if request.GET:

		oauth_code = request.GET.get('code')
		environment = request.GET.get('state')[:-2]
		api_version = request.GET.get('state')[-2:]
		access_token = ''
		instance_url = ''
		org_id = ''

		if 'Production' in environment:
			login_url = 'https://login.salesforce.com'
		else:
			login_url = 'https://test.salesforce.com'
		
		r = requests.post(login_url + '/services/oauth2/token', headers={ 'content-type':'application/x-www-form-urlencoded'}, data={'grant_type':'authorization_code','client_id': settings.SALESFORCE_CONSUMER_KEY,'client_secret':settings.SALESFORCE_CONSUMER_SECRET,'redirect_uri': settings.SALESFORCE_REDIRECT_URI,'code': oauth_code})
		auth_response = json.loads(r.text)

		if 'error_description' in auth_response:
			error_exists = True
			error_message = auth_response['error_description']
		else:
			access_token = auth_response['access_token']
			instance_url = auth_response['instance_url']
			user_id = auth_response['id'][-18:]
			org_id = auth_response['id'][:-19]
			org_id = org_id[-18:]

			# get username of the authenticated user
			r = requests.get(instance_url + '/services/data/v' + api_version + '.0/sobjects/User/' + user_id + '?fields=Username', headers={'Authorization': 'OAuth ' + access_token})
			query_response = json.loads(r.text)
			username = query_response['Username']

			# get the org name of the authenticated user
			r = requests.get(instance_url + '/services/data/v' + api_version + '.0/sobjects/Organization/' + org_id + '?fields=Name', headers={'Authorization': 'OAuth ' + access_token})
			org_name = json.loads(r.text)['Name']

		login_form = LoginForm(initial={'environment': environment, 'api_version': api_version, 'access_token': access_token, 'instance_url': instance_url, 'org_id': org_id})	

	# Run after user selects logout or get schema
	if request.POST:

		login_form = LoginForm(request.POST)

		if login_form.is_valid():

			environment = login_form.cleaned_data['environment']
			api_version = login_form.cleaned_data['api_version']
			access_token = login_form.cleaned_data['access_token']
			instance_url = login_form.cleaned_data['instance_url']
			org_id = login_form.cleaned_data['org_id']

			if 'logout' in request.POST:

				if 'Production' in environment:
					login_url = 'https://login.salesforce.com'
				else:
					login_url = 'https://test.salesforce.com'

				r = requests.post(login_url + '/services/oauth2/revoke', headers={'content-type':'application/x-www-form-urlencoded'}, data={'token': access_token})
				return HttpResponseRedirect('/logout?environment=' + environment)

			if 'get_schema' in request.POST:

				# Create schema record
				schema = Schema()
				schema.org_id = org_id
				schema.api_version = str(api_version) + '.0'
				schema.org_name = org_name
				schema.status = 'Running'
				schema.save()

				# Queue job to run async
				try:
					get_objects_and_fields.delay(schema, instance_url, api_version, org_id, access_token)
				except:
					# If fail above, wait 5 seconds and try again. Not ideal but should work for now
					sleep(5)
					try:
						get_objects_and_fields.delay(schema, instance_url, api_version, org_id, access_token)
					except:
						# Sleep another 5
						sleep(5)
						get_objects_and_fields.delay(schema, instance_url, api_version, org_id, access_token)

				return HttpResponseRedirect('/loading/' + str(schema.id))

	return render_to_response('oauth_response.html', RequestContext(request,{'error': error_exists, 'error_message': error_message, 'username': username, 'org_name': org_name, 'login_form': login_form}))

# AJAX endpoint for page to constantly check if job is finished
def job_status(request, schema_id):
	schema = get_object_or_404(Schema, pk=schema_id)
	return HttpResponse(schema.status + ':::' + schema.error)

# Page for user to wait for job to run
def loading(request, schema_id):

	schema = get_object_or_404(Schema, pk=schema_id)

	# If finished already (unlikely) direct to schema view
	if schema.status == 'Finished':
		return HttpResponseRedirect('/schema/' + str(schema.id))
	else:
		return render_to_response('loading.html', RequestContext(request, {'schema': schema}))	

def view_schema(request, schema_id):
	# Pass the schema to the page but delete it after view - it's not nice to store Orgs data models
	schema = get_object_or_404(Schema, pk=schema_id)
	return render_to_response('schema.html', RequestContext(request,{'schema': schema}))

def delete_schema(request, schema_id):

	try:
		schema = Schema.objects.get(pk = schema_id)
		schema.delete()
	except:
		pass

	return HttpResponse('Record deleted')

def logout(request):

	# Determine logout url based on environment
	environment = request.GET.get('environment')

	if 'Production' in environment:
		logout_url = 'https://login.salesforce.com'
	else:
		logout_url = 'https://test.salesforce.com'
		
	return render_to_response('logout.html', RequestContext(request, {'logout_url': logout_url}))

schemalister/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Salesforce.com Schema Lister</title>
		<meta name="keywords" content="salesforce, salesforce.com, force.com, schema, schemalister, sfschema packagebuilder, metadata, api, metadata api, package.xml, xml, destructivechanges.xml, descructivechanges, ide, force.com ide, eclipse, ant, force.com migration" /> 
  		<meta name="description" content="Build a list of objects, fields and field attributes from your Salesforce Org" />
  		<meta name="author" content="Ben Edwards (ben@benedwards.co.nz)" />
  		<meta charset="UTF-8" />

  		{% block css %}{% endblock %}
		<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/styles.css" />
		<link rel="shortcut icon" href="{{ STATIC_URL }}images/favicon.ico" type="image/vnd.microsoft.icon" />
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
		<script type="text/javascript" src="{{ STATIC_URL }}js/main.js"></script>
		{% block scripts %}{% endblock %}
	</head>	

	<body>

		<div id="wrapper">

			<a href="http://www.tquila.com" class="logo" target="_blank">
				<img src="{{ STATIC_URL }}images/tquila-logo@1x.png" style="" border="0" />
			</a>

			<div class="contact">
				<a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a>
			</div>

			<div class="clear"></div>

			<div id="container">
				{% block content %}{% endblock %}
			</div>

		</div>

	</body>

</html>

schemalister/templates/index.html
{% extends 'base.html' %}

{% block content %}

	<div class="inner">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce REST API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
		
		<table id="login_table">

			<form action="." method="POST" onsubmit="hideTable();" oncomplete="showTable();" id="loginForm"> {% csrf_token %}

				<table class="login_table">

					<tr>
						<td colspan="2" style="color:#ff6600;font-weight:bold;">
							<h2>Select Options</h2>
						</td>
					</tr>

					{% if login_form.errors or login_form.non_field_errors %}
						<tr>
							<td colspan="2" style="color:#ff6600;font-weight:bold;">
								{{ login_form.errors}} <br/>
								{{ login_form.non_field_errors }}
							</td>
						</tr>
					{% endif %}

					{% if messages %}
						<tr>
							<td colspan="2" style="color:#ff6600;font-weight:bold;">
							    {% for message in messages %}
							    	{{ message }}<br/>
							    {% endfor %}
							    <br/>
							</td>
						</tr>
					{% endif %}

					<tr>
						<td width="200">
							<label for="id_environment">Environment</label>
						</td>
						<td>
							<select id="id_environment" name="environment">
								<option value="Production">Production</option>
								<option value="Sandbox">Sandbox</option>
							</select>
						</td>
					</tr>

					<tr>
						<td>
							<label for="id_api_version">API Version</label>
						</td>
						<td>
							<select id="id_api_version" name="api_version">
								<option value="32">32.0</option>
								<option value="31">31.0</option>
								<option value="30">30.0</option>
								<option value="29">29.0</option>
								<option value="28">28.0</option>
							</select>
						</td>
					</tr>

					<tr>
						<td colspan="2">&nbsp;</td>
					</tr>

					<tr>
						<td colspan="2" style="text-align:center;height:50px;">
							<input type="submit" value="Login to Salesforce with OAuth" />
						</td>
					</tr>

				</table>

				<div class="loading">
					<div style="float:left;">
						<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Accessing Salesforce...</h1>
						<p>Logging in with OAuth 2.0</p>
					</div>
				</div>

			</form>

		</table>

	</div>

{% endblock %}

schemalister/templates/loading.html
{% extends 'base.html' %}

{% block content %}

	<div class="inner">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce REST API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
					
		<div class="loading-components">

			<div style="float:left;">
				<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
			</div>

			<div style="float:left;margin-left:20px;">
				<h1 style="font-size:1.5em;margin-top:20px;">Querying objects and fields...</h1>
				<p>This can take a few minutes.</p>
			</div>

		</div>

		<div class="error" style="display:none;">
			<p>
				There was an error processing your request: <i class="error_message"></i>
				<br/><br/>
				Please <a href="/">return</a> to the home page and try again.
			</p>
		</div>

	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job_status/{{ schema.id }}',
			    type: 'get', //this is the default though, you don't actually need to always mention it
			    success: function(resp) 
			    {
			        if (resp.split(':::')[0].trim() == 'Finished')
			        {
			        	window.location = '/schema/{{ schema.id }}/';
			        } 
			        else if (resp.split(':::')[0].trim() == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.split(':::')[1]);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 3000);
	</script>

{% endblock %}

schemalister/templates/logout.html
{% extends 'base.html' %}

{% block content %}

	<div class="inner">

		<h1>Salesforce package.xml Builder</h1>
		<p>
			Successfully logged out of Salesforce and Package Builder
		</p>

		<iframe src="https://login.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
		<iframe src="https://test.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

		<script>
			setTimeout(function () {
	       		window.location.href = "/";
	    	}, 3000);
		</script>

	</div>
{% endblock %}

schemalister/templates/oauth_response.html
{% extends 'base.html' %}

{% block content %}

	<div class="inner">

		<h1>Salesforce Schema Lister</h1>
		<p>
			This tool uses the Salesforce REST API to build a list of objects, fields and field attributes from within your Salesforce Org.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool.
		</p>
					
		<table id="login_table">

			<form action="." method="POST" id="loginForm"> {% csrf_token %}

				<table class="login_table">

					{% if messages %}

						<tr>
							<td colspan="2" style="color:#ff6600;font-weight:bold;">
							    {% for message in messages %}
							    	{{ message }}<br/>
							    {% endfor %}
							    <br/>
							</td>
						</tr>
						
					{% endif %}

					{% if not error %}

						<h2>Logged in as:</h2>

						<tr>
							<td width="150">
								<strong>Username:</strong>
							</td>
							<td>
								{{ username }}
							</td>
						</tr>

						<tr>
							<td width="150">
								<strong>Organisation:</strong>
							</td>
							<td>
								{{ org_name }}
							</td>
						</tr>

						<tr>
							<td colspan="2"></td>
						</tr>

						<tr>
							<td colspan="2" style="text-align:center;height:50px;">
								<input type="submit" name="logout" value="Logout" onclick="showLogout();" oncomplete="hideLogout();" />
								<input type="submit" name="get_schema" value="Get Schema" onclick="hideTable();" oncomplete="showTable();" />
							</td>
						</tr>

					{% else %}

					<tr>
						<td width="75" style="color:#ff6600;font-weight:bold;">
							<h2>Error: </h2>
						</td>
						<td style="color:#900;">
							{{ error_message }}
						</td>
					</tr>

					<tr>
						<td width="75" colspan="2">
							Please go <a href="/">back</a> and try again.
						</td>
					</tr>

					{% endif %}

				</table>

				<div class="loading">
					<div style="float:left;">
						<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Querying objects and fields...</h1>
						<p>This can take a few minutes.</p>
					</div>
				</div>

				<div class="logging_out">
					<div style="float:left;">
						<img src="{{ STATIC_URL }}images/loading.gif" alt="Loading" title="Loading" />
					</div>
					<div style="float:left;margin-left:20px;">
						<h1 style="font-size:1.5em;margin-top:20px;">Logging out...</h1>
						<p>Revoking OAuth token.</p>
					</div>
				</div>

				<div style="display:none;">
					{{ login_form.as_p }}
				</div>

			</form>

		</table>

	</div>

{% endblock %}

schemalister/templates/schema.html
{% extends 'base.html' %}

{% block css %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
{% endblock %}

{% block scripts %}
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
{% endblock %}

{% block content %}

	<script>
		$(document).ready(function() 
		{
			$.ajax({
			    url: '/delete_schema/{{ schema.id }}/',
			    type: 'get',
			    success: function(resp) 
			    {
			        // Else do nothing. It will re-run in 5 seconds
			    },
			    failure: function(resp) 
			    { 
			        // Do nothing
			    }
			});
		})
	</script>

	<h1>Salesforce Schema Lister</h1>
	<p>
		See the objects and fields printed below for the Org: <strong>{{ schema.org_name }}</strong> ({{ schema.org_id }}) <br/><br/>
		Note: Your actual org schema has been deleted on loading this page. Refreshing this page will error. This is to ensure none of your Org data is captured.
	</p>

	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

	    <div class="panel panel-default">

	        <div class="panel-heading" role="tab" id="headingOne">
	            <h4 class="panel-title">
	                <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="collapsed">
	                    Jump to Object
	                </a>
	            </h4>
	        </div>

	        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
	            <div class="panel-body">
	            	{% for object in schema.sorted_objects %} 
                    	<a href="#{{ object.api_name }}" class="object_link">{{ object.label }}</a> <span class="object_link">|</span> 
                    {% endfor %}
	            </div>
	        </div>

	    </div>

	</div>

	{% for object in schema.sorted_objects %}

		<a name="{{ object.api_name }}"></a>
		<h2>{{ object.label }} ({{ object.api_name }})</h2>

		<table class="table table-hover">

			<thead>
				<tr>
					<th width="30%">Field Label</th>
					<th width="30%">API Name</th>
					<th width="30%">Type</th>
				</tr>
			</thead>

			<tbody>

			{% for field in object.sorted_fields %}

				<tr>
					<td>{{ field.label }}</td>
					<td>{{ field.api_name }}</td>
					<td>{{ field.data_type|linebreaks }}</td>
				</tr>

			{% endfor %}

			</tbody>

		</table>

		<br/>

	{% endfor %}

	<a href="#" class="back-to-top">Back to Top</a>

{% endblock %}